# Generated by Django 2.0.7 on 2018-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipa',
            fields=[
                ('nazwa', models.CharField(max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trasa', models.CharField(choices=[('HS', 'Starszoharcerska'), ('W', 'Wedrownicza'), ('R', 'Rowerowa')], max_length=2)),
                ('telefon', models.CharField(max_length=64)),
                ('do_zaplaty', models.FloatField()),
                ('zaplacono', models.FloatField()),
                ('pozostalo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Uczestnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imienazwisko', models.CharField(max_length=64)),
                ('pesel', models.CharField(max_length=64)),
                ('mail', models.EmailField(max_length=64)),
                ('adres', models.CharField(max_length=64)),
                ('czy_patrolowy', models.BooleanField(default=False)),
                ('obecnosc', models.BooleanField(default=False)),
                ('uwagi', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='ekipa',
            name='czlonkowie',
            field=models.ManyToManyField(to='baza.Uczestnik'),
        ),
    ]
