# Generated by Django 2.0.7 on 2018-07-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0002_auto_20180727_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uczestnik',
            old_name='imienazwisko',
            new_name='imie_nazwisko',
        ),
    ]
