# Generated by Django 2.0.7 on 2018-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0004_auto_20180727_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kwadrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='ekipa',
            name='ile_wege',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='oswiadczenie_patrolowego',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='pakiet_startowy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='termin_wplat',
            field=models.CharField(choices=[('01/09', '01/09/2018 - 25,00'), ('01/10', '01/10/2018 - 35,00'), ('01/11', '01/11/2018 - 45,00')], default='01/09', max_length=64),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='test_poczatkowy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='uwagi',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='weryfikacja_zgod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='zaplacono_na_osobe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='zgodnosc_wplat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uczestnik',
            name='zgoda_na_udzial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='do_zaplaty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='nazwa',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='telefon',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='trasa',
            field=models.CharField(choices=[('HS', 'Starszoharcerska'), ('W', 'Wedrownicza'), ('R', 'Rowerowa')], default='HS', max_length=2),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='zaplacono',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='kwadrat_startowy',
            field=models.ManyToManyField(to='baza.Kwadrat'),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='punkty_bieg',
            field=models.ManyToManyField(to='baza.Punkt'),
        ),
    ]
