# Generated by Django 2.0.7 on 2018-07-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0005_auto_20180727_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punkt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
