# Generated by Django 2.0.7 on 2018-07-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0006_auto_20180727_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipa',
            name='weryfikacja_zgod',
        ),
    ]
