# Generated by Django 2.0.7 on 2018-07-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0007_remove_ekipa_weryfikacja_zgod'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='weryfikacja_zgod',
            field=models.BooleanField(default=False),
        ),
    ]
