# Generated by Django 2.0.7 on 2018-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0011_ekipa_ile_osob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='obecnosci',
            field=models.BooleanField(default=False),
        ),
    ]
