# Generated by Django 2.0.7 on 2018-07-30 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baza', '0013_uzytkownik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzytkownik',
            new_name='Profile',
        ),
    ]
