# Generated by Django 2.0.7 on 2018-07-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0015_auto_20180730_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('permission_code', 'Friendly permission description'),)},
        ),
    ]
