# Generated by Django 2.0.7 on 2018-07-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0017_auto_20180730_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='lp',
            field=models.IntegerField(default=0),
        ),
    ]
