# Generated by Django 2.0.7 on 2018-07-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0018_ekipa_lp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaliczonyPunkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podpowiedz', models.BooleanField(default=False)),
                ('zawieszenie', models.BooleanField(default=False)),
                ('brak_punktu', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='punkt',
            name='adres',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='punkt',
            name='odpowiedz',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='punkt',
            name='opis_zawieszenia_1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='punkt',
            name='opis_zawieszenia_2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='punkt',
            name='punktowy',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='punkt',
            name='pytanie',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='punkt',
            name='skrzyzowanie',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='punkt',
            name='trasa',
            field=models.CharField(blank=True, choices=[('HS', 'Starszoharcerska'), ('W', 'Wedrownicza'), ('R', 'Rowerowa')], default='HS', max_length=2),
        ),
        migrations.AddField(
            model_name='punkt',
            name='uwagi',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='punkt',
            name='nazwa',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='zaliczonypunkt',
            name='punkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.Punkt'),
        ),
    ]
