# Generated by Django 2.0.7 on 2018-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0019_auto_20180731_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipa',
            name='punkty_bieg',
            field=models.ManyToManyField(to='baza.ZaliczonyPunkt'),
        ),
    ]
