# Generated by Django 2.0.7 on 2018-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0021_auto_20180731_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='numer',
            field=models.IntegerField(default=0),
        ),
    ]
