# Generated by Django 2.0.7 on 2018-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0022_punkt_numer'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaliczonypunkt',
            name='uwagi',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
