# Generated by Django 2.0.7 on 2018-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0023_zaliczonypunkt_uwagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='punkty_ujemne',
            field=models.IntegerField(default=0),
        ),
    ]
