# Generated by Django 2.0.7 on 2018-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0024_ekipa_punkty_ujemne'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='punkty_za_odpowiedzi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='punkty_za_trase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekipa',
            name='wynik_koncowy',
            field=models.IntegerField(default=0),
        ),
    ]
