# Generated by Django 2.0.7 on 2018-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0025_auto_20180731_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='punkt_startowy',
            field=models.ManyToManyField(blank=True, to='baza.Punkt'),
        ),
    ]
