# Generated by Django 2.0.7 on 2018-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0026_ekipa_punkt_startowy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipa',
            name='kwadrat_startowy',
            field=models.ManyToManyField(blank=True, to='baza.Kwadrat'),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='punkty_bieg',
            field=models.ManyToManyField(blank=True, to='baza.ZaliczonyPunkt'),
        ),
    ]
