# Generated by Django 2.0.7 on 2018-07-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0027_auto_20180731_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ekipa',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='kwadrat',
            options={'ordering': ('nazwa',)},
        ),
        migrations.AlterModelOptions(
            name='punkt',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='termin',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='uczestnik',
            options={'ordering': ('imie_nazwisko',)},
        ),
        migrations.AlterModelOptions(
            name='zaliczonypunkt',
            options={'ordering': ('id',)},
        ),
    ]
