# Generated by Django 2.0.7 on 2018-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0028_auto_20180731_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punkt',
            options={'ordering': ('numer',)},
        ),
    ]
