# Generated by Django 2.1 on 2018-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0031_punkt_hs_zgloszenie_hs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipa',
            name='punkt_startowy',
            field=models.ManyToManyField(blank=True, to='baza.Punkt_HS'),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='punkty_bieg',
            field=models.ManyToManyField(blank=True, to='baza.Zgloszenie_HS'),
        ),
    ]
