# Generated by Django 2.1 on 2018-08-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0032_auto_20180815_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punkt_hs',
            options={},
        ),
        migrations.RemoveField(
            model_name='punkt',
            name='trasa',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='dojscie',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='kod',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='nazwa',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='numer',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='odpowiedz',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='opis_zawieszenia_1',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='opis_zawieszenia_2',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='punktowy',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='pytanie',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='skrzyzowanie',
        ),
        migrations.RemoveField(
            model_name='punkt_hs',
            name='uwagi',
        ),
        migrations.AddField(
            model_name='punkt_hs',
            name='punkt_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Punkt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punkt_hs',
            name='trasa',
            field=models.CharField(blank=True, choices=[('HS', 'Starszoharcerska'), ('W', 'Wedrownicza'), ('R', 'Rowerowa')], default='HS', max_length=2),
        ),
    ]
