# Generated by Django 2.1 on 2018-08-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0033_auto_20180815_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punkt_R',
            fields=[
                ('punkt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Punkt')),
                ('trasa', models.CharField(blank=True, default='R', max_length=2)),
            ],
            bases=('baza.punkt',),
        ),
        migrations.CreateModel(
            name='Punkt_W',
            fields=[
                ('punkt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Punkt')),
                ('trasa', models.CharField(blank=True, default='W', max_length=2)),
            ],
            bases=('baza.punkt',),
        ),
        migrations.AlterField(
            model_name='punkt_hs',
            name='trasa',
            field=models.CharField(blank=True, default='HS', max_length=2),
        ),
    ]
