# Generated by Django 2.1 on 2018-08-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0034_auto_20180815_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipa',
            name='punkt_startowy',
        ),
        migrations.RemoveField(
            model_name='ekipa',
            name='punkty_bieg',
        ),
    ]
