# Generated by Django 2.1 on 2018-08-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0036_remove_zgloszenie_hs_punkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie_hs',
            name='punkt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='baza.Punkt_HS'),
            preserve_default=False,
        ),
    ]
