# Generated by Django 2.1 on 2018-08-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0037_zgloszenie_hs_punkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('podpowiedz', models.BooleanField(default=False)),
                ('zawieszenie', models.BooleanField(default=False)),
                ('brak_punktu', models.BooleanField(default=False)),
                ('uwagi', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='zgloszenie_hs',
            options={},
        ),
        migrations.RemoveField(
            model_name='zgloszenie_hs',
            name='brak_punktu',
        ),
        migrations.RemoveField(
            model_name='zgloszenie_hs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='zgloszenie_hs',
            name='podpowiedz',
        ),
        migrations.RemoveField(
            model_name='zgloszenie_hs',
            name='uwagi',
        ),
        migrations.RemoveField(
            model_name='zgloszenie_hs',
            name='zawieszenie',
        ),
        migrations.AddField(
            model_name='zgloszenie_hs',
            name='zgloszenie_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Zgloszenie'),
            preserve_default=False,
        ),
    ]
