# Generated by Django 2.1 on 2018-08-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0038_auto_20180815_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zgloszenie_R',
            fields=[
                ('zgloszenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Zgloszenie')),
                ('punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.Punkt_R')),
            ],
            bases=('baza.zgloszenie',),
        ),
        migrations.CreateModel(
            name='Zgloszenie_W',
            fields=[
                ('zgloszenie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Zgloszenie')),
                ('punkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza.Punkt_W')),
            ],
            bases=('baza.zgloszenie',),
        ),
    ]
