# Generated by Django 2.1 on 2018-08-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0040_auto_20180815_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('WidokGlowny', 'Dostęp do strony głównej'), ('Punkty', 'Wyświetlanie punktów'), ('PunktyHS', 'HS Wyświetlanie punktów'), ('PunktyW', 'W Wyświetlanie punktów'), ('PunktyR', 'R Wyświetlanie punktów'), ('Kwadraty', 'Wyświetlanie kwadratów'), ('Ekipy', 'Wyświetlanie szczegółów ekip'), ('Uczestnicy', 'Wyświetlanie uczestników'))},
        ),
    ]
