# Generated by Django 2.1 on 2018-08-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0041_auto_20180815_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaliczonypunkt',
            name='punkt',
        ),
        migrations.DeleteModel(
            name='ZaliczonyPunkt',
        ),
    ]
