# Generated by Django 2.1 on 2018-08-15 22:10

import baza.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0042_auto_20180815_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipa',
            name='punkt_punktowy',
            field=models.ManyToManyField(blank=True, choices=[(baza.models.Punkt_W, 'P Wedrownicza'), (baza.models.Punkt_R, 'P Rowerowa')], to='baza.Punkt_W'),
        ),
    ]
