# Generated by Django 2.1 on 2018-08-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0043_ekipa_punkt_punktowy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipa',
            name='punkt_punktowy',
        ),
    ]
