# Generated by Django 2.1 on 2018-08-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0045_auto_20180816_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkipaR',
            fields=[
                ('nazwa', models.CharField(default='', max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefon', models.CharField(default='', max_length=64)),
                ('zaplacono', models.FloatField(default=0)),
                ('ile_osob', models.IntegerField(default=0)),
                ('lp', models.IntegerField(default=0)),
                ('do_zaplaty', models.FloatField(default=0)),
                ('zaplacono_na_osobe', models.FloatField(default=0)),
                ('pozostalo', models.FloatField(default=0)),
                ('zgodnosc_wplat', models.BooleanField(default=False)),
                ('oswiadczenie_patrolowego', models.BooleanField(default=False)),
                ('obecnosci', models.BooleanField(default=False)),
                ('weryfikacja_zgod', models.BooleanField(default=False)),
                ('pakiet_startowy', models.BooleanField(default=False)),
                ('ile_wege', models.IntegerField(default=0)),
                ('uwagi', models.CharField(blank=True, default='', max_length=256)),
                ('test_poczatkowy', models.IntegerField(default=0)),
                ('punkty_za_trase', models.IntegerField(default=0)),
                ('punkty_za_odpowiedzi', models.IntegerField(default=0)),
                ('punkty_ujemne', models.IntegerField(default=0)),
                ('wynik_koncowy', models.IntegerField(default=0)),
                ('trasa', models.CharField(default='R', max_length=2)),
                ('czlonkowie', models.ManyToManyField(to='baza.Uczestnik')),
                ('kwadrat_startowy', models.ManyToManyField(blank=True, to='baza.Kwadrat')),
                ('punkt_startowy', models.ManyToManyField(blank=True, to='baza.Punkt_R')),
                ('punkty_bieg', models.ManyToManyField(blank=True, to='baza.Zgloszenie_R')),
                ('termin_wplat', models.ManyToManyField(to='baza.Termin')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ekipaw',
            name='trasa',
            field=models.CharField(default='W', max_length=2),
        ),
    ]
