# Generated by Django 2.1 on 2018-08-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0046_auto_20180816_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipa',
            fields=[
                ('nazwa', models.CharField(default='', max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trasa', models.CharField(choices=[('HS', 'Starszoharcerska'), ('W', 'Wedrownicza'), ('R', 'Rowerowa')], default='HS', max_length=2)),
                ('telefon', models.CharField(default='', max_length=64)),
                ('zaplacono', models.FloatField(default=0)),
                ('ile_osob', models.IntegerField(default=0)),
                ('lp', models.IntegerField(default=0)),
                ('do_zaplaty', models.FloatField(default=0)),
                ('zaplacono_na_osobe', models.FloatField(default=0)),
                ('pozostalo', models.FloatField(default=0)),
                ('zgodnosc_wplat', models.BooleanField(default=False)),
                ('oswiadczenie_patrolowego', models.BooleanField(default=False)),
                ('obecnosci', models.BooleanField(default=False)),
                ('weryfikacja_zgod', models.BooleanField(default=False)),
                ('pakiet_startowy', models.BooleanField(default=False)),
                ('ile_wege', models.IntegerField(default=0)),
                ('uwagi', models.CharField(blank=True, default='', max_length=256)),
                ('test_poczatkowy', models.IntegerField(default=0)),
                ('punkty_za_trase', models.IntegerField(default=0)),
                ('punkty_za_odpowiedzi', models.IntegerField(default=0)),
                ('punkty_ujemne', models.IntegerField(default=0)),
                ('wynik_koncowy', models.IntegerField(default=0)),
                ('czlonkowie', models.ManyToManyField(to='baza.Uczestnik')),
                ('kwadrat_startowy', models.ManyToManyField(blank=True, to='baza.Kwadrat')),
                ('punkt_startowy', models.ManyToManyField(blank=True, to='baza.Punkt_HS')),
                ('punkty_bieg', models.ManyToManyField(blank=True, to='baza.Zgloszenie_HS')),
                ('termin_wplat', models.ManyToManyField(to='baza.Termin')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='ekipar',
            name='czlonkowie',
        ),
        migrations.RemoveField(
            model_name='ekipar',
            name='kwadrat_startowy',
        ),
        migrations.RemoveField(
            model_name='ekipar',
            name='punkt_startowy',
        ),
        migrations.RemoveField(
            model_name='ekipar',
            name='punkty_bieg',
        ),
        migrations.RemoveField(
            model_name='ekipar',
            name='termin_wplat',
        ),
        migrations.RemoveField(
            model_name='ekipaw',
            name='czlonkowie',
        ),
        migrations.RemoveField(
            model_name='ekipaw',
            name='kwadrat_startowy',
        ),
        migrations.RemoveField(
            model_name='ekipaw',
            name='punkt_startowy',
        ),
        migrations.RemoveField(
            model_name='ekipaw',
            name='punkty_bieg',
        ),
        migrations.RemoveField(
            model_name='ekipaw',
            name='termin_wplat',
        ),
        migrations.DeleteModel(
            name='EkipaR',
        ),
        migrations.DeleteModel(
            name='EkipaW',
        ),
    ]
