# Generated by Django 2.0.7 on 2018-08-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0047_auto_20180816_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipa_HS',
            fields=[
                ('ekipa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Ekipa')),
                ('trasy', models.CharField(blank=True, default='HS', max_length=2)),
            ],
            bases=('baza.ekipa',),
        ),
        migrations.CreateModel(
            name='Ekipa_R',
            fields=[
                ('ekipa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Ekipa')),
                ('trasy', models.CharField(blank=True, default='R', max_length=2)),
            ],
            bases=('baza.ekipa',),
        ),
        migrations.CreateModel(
            name='Ekipa_W',
            fields=[
                ('ekipa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='baza.Ekipa')),
                ('trasy', models.CharField(blank=True, default='W', max_length=2)),
            ],
            bases=('baza.ekipa',),
        ),
    ]
