# Generated by Django 2.0.7 on 2018-08-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0048_ekipa_hs_ekipa_r_ekipa_w'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('WidokGlowny', 'Strona Główna'), ('Punkty', 'Wszystkie punkty'), ('PunktyHS', 'HS punkty'), ('PunktyW', 'W punkty '), ('PunktyR', 'R punkty '), ('Kwadraty', 'Kwadraty'), ('Ekipy', 'Wszystkie ekipy '), ('EkipyHS', 'HS ekipy '), ('EkipyW', 'W ekipy '), ('EkipyR', 'R ekipy'), ('Uczestnicy', 'Wyświetlanie uczestników'))},
        ),
    ]
