# Generated by Django 2.1 on 2018-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0049_auto_20180816_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='punkt',
            name='foto',
            field=models.ImageField(blank=True, default='baza/static/no-image.jpg', upload_to='baza/static/'),
        ),
    ]
