# Generated by Django 2.1 on 2018-09-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0050_punkt_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punkt',
            name='foto',
            field=models.ImageField(blank=True, default='baza/static/foto/{self.id}.jpg', upload_to='baza/static/foto/'),
        ),
    ]
