# Generated by Django 2.0.7 on 2018-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0051_auto_20180915_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipa',
            name='ile_osob',
            field=models.IntegerField(default=1),
        ),
    ]
