# Generated by Django 2.1 on 2018-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0052_auto_20181007_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uczestnik',
            name='adres',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='uczestnik',
            name='mail',
            field=models.EmailField(blank=True, max_length=64),
        ),
    ]
