# Generated by Django 2.1 on 2018-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0053_auto_20181018_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczestnik',
            name='wiek',
            field=models.CharField(blank=True, default='10', max_length=2),
        ),
        migrations.AlterField(
            model_name='ekipa',
            name='termin_wplat',
            field=models.ManyToManyField(blank=True, to='baza.Termin'),
        ),
    ]
