# Generated by Django 2.1 on 2018-10-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0054_auto_20181020_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlikCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(default='plik_csv', max_length=50)),
                ('plik', models.FileField(upload_to='xls/')),
            ],
        ),
    ]
