# Generated by Django 2.1 on 2018-10-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza', '0055_plikcsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plikcsv',
            name='tytul',
        ),
        migrations.AddField(
            model_name='plikcsv',
            name='nazwa',
            field=models.CharField(default='nazwij_swoj_plik', max_length=50),
        ),
    ]
